name: License & Copyright Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  scancode:
    runs-on: ubuntu-latest
    steps:
      - name: Run ScanCode Analysis
        uses: JH-OSPO/scancode-action@v1
        with:
          scan-path: "."
          output-name: "scancode-results"